vipshop/TupleNet

- .travis.yml
- src/tests/ovs_utils.sh
- src/tests/test_simple_outside.sh
- src/tests/test_simple_tpcnm.sh
- src/tests/test_smoke_ls.sh
- src/tests/utils.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/lcp/state_update.py
1. it downloads ovs and compile then install ovs.
2. build tuplenet
3. update testcase to give more toleration on testing
4. update lcp/state_update.py to accerlate touching chassis entity
5. update commit_ovs.py to fix a insert ovsport bug
> Adding a travis.yml to trigger building

- src/tests/ovs_utils.sh
- src/tests/test_simple_hv.sh
- src/tests/test_simple_redirect.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/tunnel.py
- src/tuplenet/lcp/tuplerun.py
- src/tuplenet/lcp/tuplesync.py
- src/tuplenet/version.py
1. update commit_ovs to use replace-flow to insert flows
2. bump version to 0.1.10
3. update tunnel.py to get unused tunnel port
> do not clear tunnel-ports and ovs-flows when restarting tuplenet #3

- src/tuplenet/lcp/tuplerun.py
1. increase(50MB->2000MB) the log size in RotatingFileHandler
> increase the log size in RotatingFileHandler

- src/tuplenet/lcp/tuplerun.py
1. always set extra['log_dir'], pkt_controler will read it to know
if it print log to that folder.
> Fix log file path issue

- .travis.yml
- src/tuplenet/lcp/action.py
- src/tuplenet/lcp/link_master.py
- src/tuplenet/lcp/reg.py
- src/tuplenet/pkt_controller/configure.ac
- src/tuplenet/pkt_controller/pkt_controller.c
- src/tuplenet/tools/pkt-trace.py
- src/tuplenet/version.py
1. consume controller(pause) to capture packet and send packet
back after updatting seq by pkt_controller.
2. tools/pkt-trace.py use etcd3 instreading using etcdctl.
3. update .travis.yml to get ovs2.10.1 to build&test.
4. bump version to 0.1.12
>  Consume controller(pause) to implement new pkt-tracing 

- src/tests/test_simple_trace.sh
- src/tests/test_smoke_trace.sh
- src/tests/tuplenet_utils.sh
- src/tuplenet/lcp/tuplerun.py
- src/tuplenet/pkt_controller/pkt_controller.c
- src/tuplenet/tools/pkt-trace.py
- src/tuplenet/version.py
1. do not print to console in tuplerun.py if it has log_dir
2. do not print log to console & syslog if pkt_controller has log dir
3. update tools/pkt-trace.py to make it accept config file which
contains inject port, src/dst mac, src/dst ip
4. Bump version from 0.1.12 to 0.1.13
>  Update tools/pkt-trace.py to make it accept config file and  Do not print log to console if user has config the log dir 

- src/tuplenet/lcp/lflow.py
- src/tuplenet/lcp/middle_table.py
- src/tuplenet/lcp/physical_flow.py
- src/tuplenet/lcp/pkt_trace.py
- src/tuplenet/lcp/run_env.py
- src/tuplenet/lcp/test.py
- src/tuplenet/lcp/tunnel.py
- src/tuplenet/lcp/tuplesync.py
- src/tuplenet/version.py
1. Eliminate the init_trigger
2. insert const ovs-flow when booting tuplenet
3. bump version from 0.1.13 to 0.1.14
> Eliminate the init_trigger

- src/tests/test_simple_bfd.sh
- src/tuplenet/lcp/tuplesync.py
1. now rebooting tuplenet does not regenerate tunnel-port, so
ecmp.ecmp_bfd_port(PORT_NAME, State) may generate data like
tupleNet-3232261123 1
tupleNet-3232261123 -100
It may lead to disable bfd on tunnel-port
2. update test_simple_bfd.sh to test it
> Fix bfd config error

- src/tests/test_simple_lr.sh
- src/tests/test_simple_ls.sh
- src/tuplenet/lcp/action.py
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/lcp/link_master.py
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/pkt_trace.py
- src/tuplenet/lcp/state_update.py
- src/tuplenet/lcp/tentacle.py
- src/tuplenet/lcp/tuplerun.py
- src/tuplenet/lcp/tuplesync.py
1. Eliminate unused import and unused code
2. consume tpctl in test_simple_lr.sh, test_simple_ls.sh
> Eliminate unused import and unused code

- src/tests/test_simple_trace.sh
- src/tests/tuplenet_utils.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/lcp/tuplesync.py
- src/tuplenet/tools/pkt-trace.py
1. implement auto-detect network in tools/pkt-trace.py, it can randomly
choose src_port and dst to send packet and then to verify if the whole
path is correct.
2. udpate test_simple_trace.sh to test this feature
> implement auto-detect network in tools/pkt-trace.py

- src/tuplenet/lcp/lrp_egress.py
1. update clause opposite_side_changed_lsp to add flow if the lsp
has chassis
> update clause opposite_side_changed_lsp

- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/test.py
1. the properties checking if a O(n) time process, make it become O(1) by
using dict
2. update test.py
> Optimize the properties checking

- src/tuplenet/lcp/lsp_ingress.py
- src/tuplenet/lcp/test.py
- src/tuplenet/lcp/tuplerun.py
1. Optimize the lsp_untunnel clause
2. udpate test.py
3. tuplenet output error/warning log to another files as well
> Optimize the lsp_untunnel caluse

- src/tests/test_simple_delete.sh
- src/tests/test_simple_ecmp3.sh
- src/tests/test_simple_trace.sh
- src/tests/test_smoke_trace.sh
- src/tests/tuplenet_utils.sh
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/tools/edge-operate.py
- src/tuplenet/tools/pkt-trace.py
1. make sure OFPORT should be a valid portnum(value > 0)
2. revise test_simple_trace.sh test_smoke_trace.sh
3. tools/edge-operate.py can helps to add/init/remove ecmp path into
LR-central.
4. add testcase test_simple_ecmp3.sh to test tools/edge-operate.py
5. update test_simple_delete.sh
>  Update logicalview.py clause  and  Make a new too tools/edge-operate.py

- src/tests/test_simple_ecmp3.sh
- src/tests/test_simple_redirect.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/lcp/tuplerun.py
1. set br-int fail-mode to secure
2. update test_simple_redirect.sh to add more testcase if edge tuplenet down
3. revise log format
> set br-int fail-mode to secure

- src/tests/ovs_utils.sh
- src/tests/test_simple_bfd.sh
- src/tests/test_simple_chdel.sh
- src/tests/test_simple_dnat.sh
- src/tests/test_simple_outside.sh
- src/tuplenet/lcp/ecmp.py
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/lrp_egress.py
- src/tuplenet/lcp/lrp_ingress.py
1. update test_simple_chdel.sh and pay more time in waiting bfd-sync
2. update test_simple_bfd.sh add more case
3. update ecmp.py to grep out bfd config if local chassis comes back
> Give more time in waiting bfd status in test_simple_chdel.sh

- src/tests/test_simple_redirect.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/pkt_controller/pkt_controller.c
1. update test_simple_redirect.sh
2. update pkt_controller.c to print less log
3. update commit_ovs.py to verify ofport number before adding to datalog dataset
> Update testcase test_simple_redirect.sh

- src/control/tpcni/tpcni.go
- src/tests/test_simple_redirect.sh
- src/tuplenet/lcp/lrp_egress.py
- src/tuplenet/version.py
1. fix deleteing ovsport issue in tpcni
2. lrp_egress.py was updated to avoid delivering unknow-dst packet
to controller if its ONDEMAND=0
3. bump version to 0.2.3
> Fix tpcni and edge redirecting issue

- src/tests/test_simple_ecmp3.sh
- src/tuplenet/lcp/ecmp.py
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/lsp_egress.py
- src/tuplenet/lcp/lsp_ingress.py
- src/tuplenet/lcp/physical_flow.py
- src/tuplenet/lcp/tpstatic.py
- src/tuplenet/tools/edge-operate.py
- src/tuplenet/version.py
1. bump version to 0.3.0
2. update edge-operate.py, the remove operation would not using local system-id anymore
3. update test_simple_ecmp3.sh
4. create a new file tpstatic.py which store some public static variable
> bump version to 0.3.0

- src/tests/ovs_utils.sh
- src/tests/test_simple_ecmp3.sh
- src/tests/test_simple_etcd.sh
- src/tests/test_simple_hv.sh
- src/tests/test_simple_tpcni.sh
- src/tuplenet/lcp/logicalview.py
- src/tuplenet/lcp/tuplesync.py
- src/tuplenet/tools/edge-operate.py
- src/tuplenet/version.py
1. fix re-adding chassis back to etcd side while user delete chassis in etcd side.
2. add ip2int function in logicalview.py to avoid invalid ip format.
3. fix bug in edge-operate.py while init ecmp road
4. bump version from 0.3.0 to 0.3.1
> Fix re-add chassis issue and edge-operate.py bug

- src/tests/tuplenet_utils.sh
- src/tuplenet/lcp/commit_ovs.py
- src/tuplenet/tools/edge-operate.py
1. currently the edge-operate.py logic is complex, the datalog
can help to reduce computing.
2. rewrite some import logic of edge-operate.py
3. update testcase file
> introducing pydatalog into edge-operate.py[vip:TupleNet-vip#1]

- src/control/api/model.go
modified:   src/control/api/model.go
> fix init get etcd address bug [vip:TupleNet-vip#3]

- .travis.yml
- setup.py
- src/control/go.mod
- src/control/go.sum
1. Fix go mod issue due to the belogik was deleted
2. consume python-etcd3 0.10.0 version
> Fix go mod issue, and python-etcd3 version issue
